/-
  Girard's Paradox — term-mode proofs
  =====================================
  Definitions are identical to Girard.lean.
  All theorems are in term mode, generated by the Lean compiler via #print.
-/

universe u

set_option linter.unusedVariables false


-- ============================================================
-- §1  Posets and well-foundedness
-- ============================================================

/-- A relation is transitive when x < y and y < z imply x < z. -/
def isTrans {T : Type u} (rel : T → T → Prop) : Prop :=
  ∀ {a b c : T}, rel a b → rel b c → rel a c

/-- A relation is well-founded when there is no infinite descending chain
    … < xₙ < xₙ₋₁ < … < x₁ < x₀. -/
def isWF {T : Type u} (rel : T → T → Prop) : Prop :=
  ¬ ∃ f : Nat → T, ∀ n : Nat, rel (f (n + 1)) (f n)

/-- A well-founded poset bundles a carrier type with its transitive,
    well-founded strict order. -/
structure WFPoset (T : Type u) where
  rel   : T → T → Prop
  trans : isTrans rel
  wf    : isWF rel


-- ============================================================
-- §2  The collection 𝒫 of all well-founded posets
-- ============================================================

/-- `PType` is the collection of all well-founded posets at universe level u. -/
structure PType where
  T       : Type u
  carrier : WFPoset T


-- ============================================================
-- §3  The ordering ≺ on 𝒫
-- ============================================================

/-- `pLt S R` (written S ≺ R) holds when there is an order-preserving
    map φ : S.T → R.T whose image has an upper bound in R.T. -/
def pLt (S R : PType.{u}) : Prop :=
  ∃ (φ : S.T → R.T),
    (∀ (x y : S.T), S.carrier.rel x y → R.carrier.rel (φ x) (φ y)) ∧
    (∃ (r : R.T), ∀ (x : S.T), R.carrier.rel (φ x) r)

/-- ≺ is transitive: compose the maps and keep the outer bound. -/
theorem pLt_isTrans : isTrans pLt :=
  fun {a b c : PType} (h : pLt a b) =>
    match h with
    | Exists.intro f ⟨hf_ord, Exists.intro _ hf_bnd⟩ => fun (h : pLt b c) =>
      match h with
      | Exists.intro g ⟨hg_ord, Exists.intro rc hg_bnd⟩ =>
        Exists.intro (g ∘ f)
          ⟨fun (x y : a.T) (h : a.carrier.rel x y) => hg_ord (f x) (f y) (hf_ord x y h),
            Exists.intro rc fun (x : a.T) => hg_bnd (f x)⟩


-- ============================================================
-- §4  𝒫 with ≺ is itself well-founded
-- ============================================================

/-- (𝒫, ≺) has no infinite descending chain.
    Given chain(0) ≻ chain(1) ≻ …, compose the linking maps φₙ into
    ψₙ : chain(n) → chain(0), then n ↦ ψₙ(rₙ) descends in chain(0). -/
theorem pLt_isWF : isWF pLt :=
  fun (h : ∃ (f : Nat → PType), ∀ (n : Nat), pLt (f (n + 1)) (f n)) =>
    match h with
    | Exists.intro chain hchain =>
      let φ       := fun (n : Nat) => Exists.choose (hchain n)
      let hφ_spec := fun (n : Nat) => Exists.choose_spec (hchain n)
      let hφ_ord  := fun (n : Nat) => (hφ_spec n).left
      let r       := fun (n : Nat) => (hφ_spec n).right.choose
      let hr      := fun (n : Nat) => Exists.choose_spec (hφ_spec n).right
      let ψ       := fun (n : Nat) =>
        Nat.rec (motive := fun (n : Nat) => (chain n).T → (chain 0).T) id
          (fun (k : Nat) (ψk : (chain k).T → (chain 0).T) => ψk ∘ φ k) n
      let hψ_ord  := fun (n : Nat) =>
        Nat.recAux
          (motive := fun (n : Nat) =>
            ∀ (x y : (chain n).T),
              (chain n).carrier.rel x y → (chain 0).carrier.rel (ψ n x) (ψ n y))
          (fun (x y : (chain 0).T) (h : (chain 0).carrier.rel x y) => h)
          (fun (n : Nat)
              (ih : ∀ (x y : (chain n).T),
                (chain n).carrier.rel x y → (chain 0).carrier.rel (ψ n x) (ψ n y))
              (x y : (chain (n + 1)).T) (h : (chain (n + 1)).carrier.rel x y) =>
            ih (φ n x) (φ n y) (hφ_ord n x y h))
          n
      (chain 0).carrier.wf
        (Exists.intro (fun (n : Nat) => ψ n (r n))
          fun (n : Nat) => hψ_ord n (φ n (r (n + 1))) (r n) (hr n (r (n + 1))))


-- ============================================================
-- §5  Initial segments
-- ============================================================

/-- The initial segment of S at r is the sub-poset of all elements strictly
    below r.  It is again a well-founded poset. -/
def initSeg (S : PType.{u}) (r : S.T) : PType.{u} where
  T       := {y : S.T // S.carrier.rel y r}
  -- Inherit the relation and its properties from S
  carrier := ⟨fun x y => S.carrier.rel x.1 y.1,
              fun h1 h2 => S.carrier.trans h1 h2,
              fun ⟨c, hc⟩ => S.carrier.wf ⟨fun n => (c n).1, hc⟩⟩

/-- x < y in S implies Sₓ ≺ Sᵧ (inclusion map, bound ⟨x, h⟩). -/
theorem initSeg_lt {S : PType.{u}} {x y : S.T} (h : S.carrier.rel x y) :
    pLt (initSeg S x) (initSeg S y) :=
  Exists.intro
    (fun (x_1 : (initSeg S x).T) =>
      match x_1 with
      | ⟨z, hz⟩ => ⟨z, S.carrier.trans hz h⟩)
    ⟨fun (_ _ : (initSeg S x).T) (hrel : (initSeg S x).carrier.rel _ _) => hrel,
      Exists.intro ⟨x, h⟩ fun (h_1 : (initSeg S x).T) =>
        match h_1 with
        | ⟨_, hz⟩ => hz⟩

/-- The initial segment Sₜ is strictly below S in ≺ (inclusion map, bound t). -/
theorem initSeg_lt_self (S : PType.{u}) (t : S.T) : pLt (initSeg S t) S :=
  Exists.intro
    (fun (x : (initSeg S t).T) =>
      match x with
      | ⟨s, _⟩ => s)
    ⟨fun (_ _ : (initSeg S t).T) (h : (initSeg S t).carrier.rel _ _) => h,
      Exists.intro t fun (h : (initSeg S t).T) =>
        match h with
        | ⟨_, hs⟩ => hs⟩


-- ============================================================
-- §6  Girard's Paradox
-- ============================================================

/-- No type in universe u surjects onto PType.{u}. -/
theorem girard {T : Type u} (f : T → PType.{u})
    (h_surj : ∀ s : PType.{u}, ∃ t : T, f t = s) : False :=
  let sec        := fun (s : PType) => (h_surj s).choose
  let hsec       := fun (s : PType) => Exists.choose_spec (h_surj s)
  let relT       := fun (x y : T) => pLt (f x) (f y)
  have relT_trans := fun {a b c : T} (h1 : relT a b) (h2 : relT b c) => pLt_isTrans h1 h2
  have relT_wf    := fun (x : ∃ (f : Nat → T), ∀ (n : Nat), relT (f (n + 1)) (f n)) =>
    match x with
    | Exists.intro c hc => pLt_isWF (Exists.intro (f ∘ c) hc)
  let P          := { T := T, carrier := { rel := relT, trans := fun {a b c : T} => relT_trans,
                                           wf := relT_wf } }
  let g          := fun (t : T) => sec (initSeg P t)
  let hfg        := fun (t : T) => hsec (initSeg P t)
  let hg_ord     := fun (x y : T) (hxy : relT x y) =>
    Eq.mpr (id (congrArg (fun (_a : PType) => pLt _a (f (g y))) (hfg x)))
      (Eq.mpr (id (congrArg (fun (_a : PType) => pLt (initSeg P x) _a) (hfg y)))
        (initSeg_lt hxy))
  let hg_bnd     := fun (x : T) =>
    Eq.mpr (id (congrArg (fun (_a : PType) => pLt _a (f (sec P))) (hfg x)))
      (Eq.mpr (id (congrArg (fun (_a : PType) => pLt (initSeg P x) _a) (hsec P)))
        (initSeg_lt_self P x))
  pLt_isWF (Exists.intro (fun (_ : Nat) => P)
    fun (_ : Nat) => Exists.intro g ⟨hg_ord, Exists.intro (sec P) hg_bnd⟩)
